version: '3.1'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: Det025
    command: mongod --port 2576
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb_data:/data/db
      
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data: